## This file is a template remove the .template to use the file

libraries:                           # This is called out once within the config.yml file
  Movies:                            # These are names of libraries in your Plex
    remove_overlays: false             # Set this to true to remove all overlays
    collection_files:
      # This line points to the templated file on Github
      #- url: https://raw.githubusercontent.com/sl4ppy/kometa/main/collections/movie-requests.yml
      # This line points to the local copy of the file for customization
      - file: config/collections/movie-requests.yml
      
      - url: https://raw.githubusercontent.com/sl4ppy/kometa/main/collections/holidays/holiday-movies.yml
      #- repo: collections/holidays/movies
      - repo: collections/random/movies
      - repo: collections/separators/movies

      - default: tautulli
      - default: universe

      # see the wiki for how to use local files, folders, URLs, or files from git
    overlay_files:
      - default: ribbon                                       # This is a file within PMM's defaults folder
        template_variables:
          style: red
          weight_rotten: 20
          weight_imdb: 0
      - default: resolution
        template_variables:
          use_edition: true
      - default: ratings
        template_variables:
          rating1: critic
          rating1_image: rt_tomato
          rating1_font: config/metadata/overlays/fonts/Adlib.ttf
          rating1_font_size: 70

          rating2: audience
          rating2_image: rt_popcorn
          rating2_font: config/metadata/overlays/fonts/Impact.ttf
          rating2_font_size: 50

          horizontal_position: right
      - default: versions

    settings:
      asset_directory: config/assets/Movies/
      prioritize_assets: true                         # The asset_directory contains folders per media item with respective posters   

    operations:
      split_duplicates: false                         # Splits all duplicate movies/shows found in this library
      assets_for_all: false                           # Search in assets for images for every item in your library
      delete_collections:
        configured: false                             # False - Collection must be an Unconfigured Collection to be deleted (collection is not in the config file of the specific PMM run).
        managed: false                                # False - Collection must be an Unmanaged Collection to be deleted (the collection does not have the PMM label)
        less: 2
      mass_user_rating_update: mdb_tomatoes           # Update user ratings with mdb_tomatoes
      mass_critic_rating_update: mdb_tomatoes         # Update critic ratings with imdb
      mass_audience_rating_update: mdb_tomatoesaudience # Update audience ratings with tmdb
      mass_genre_update: tmdb                         # Update all genres from tmdb
      mass_content_rating_update: mdb_commonsense     # Changes Content Rating to "1", "2" etc. to specify appropriate age
      mass_originally_available_update: tmdb          # Update all original available date from tmdb
      mass_imdb_parental_labels: none                 # Apply all Parental Labels with a value of None, Mild, Moderate, or Severe to match IMDb parental guide





  # see the wiki for how to use local files, folders, URLs, or files from git
  TV Shows:
    remove_overlays: false           # Set this to true to remove all overlays
    report_path: config/missing/TV_report.yml
    collection_files:
      # This line points to the templated file on Github
      #- url: https://raw.githubusercontent.com/sl4ppy/kometa/main/collections/series-requests.yml

      # This line points to the local copy of the file for customization
      - file: config/collections/series-requests.yml
      - repo: collections/new/shows
      - repo: collections/separators/shows 

    overlay_files:
      - url: https://raw.githubusercontent.com/sl4ppy/kometa/main/overlays/status.yml
      - url: https://raw.githubusercontent.com/sl4ppy/kometa/main/overlays/network_fallback.yml
      - url: https://raw.githubusercontent.com/sl4ppy/kometa/main/overlays/overlay_shows.yml
      
      - default: network
        template_variables:
          horizontal_align: left
          horizontal_offset: 0
          vertical_offset: 0
          vertical_align: top
          back_width: 1000
          back_height: 1500
          #file: config/overlays/network-top-left/<<key>>.png
          #file_#0: config/overlays/network-top-left/#0.png
          url: https://raw.githubusercontent.com/sl4ppy/kometa/main/overlays/network-top-left/<<key>>.png
          url_#0:  https://raw.githubusercontent.com/sl4ppy/kometa/main/overlays/network-top-left/%230.png
          back_color: 00 

      - default: ratings
        template_variables:
          builder_level: Episode
          minimum_items: 1
          
          rating1: critic
          rating1_image: rt_tomato
          rating1_font: config/metadata/overlays/fonts/Impact.ttf
          rating1_font_size: 70

          rating2: audience
          rating2_image: rt_popcorn
          rating2_font: config/metadata/overlays/fonts/Adlib.ttf
          rating2_font_size: 63

          rating3: user
          rating3_image: tmdb
          rating3_font: config/metadata/overlays/fonts/Avenir_95_Black.ttf
          rating3_font_size: 70

          horizontal_position: right
      
      # - default: ratings
      #   template_variables:
      #     builder_level: episode

      #     rating1: critic
      #     rating1_image: imdb
      #     rating1_font: config/metadata/fonts/Impact.ttf
      #     rating1_font_size: 70

      #     rating2: audience
      #     rating2_image: tmdb
      #     rating2_font: config/metadata/fonts/Avenir_95_Black.ttf
      #     rating2_font_size: 70

      #     horizontal_position: right
    operations:
      mass_critic_rating_update: mdb_tomatoes
      mass_audience_rating_update: mdb_tomatoesaudience
      mass_user_rating_update: mdb_tomatoes
      mass_episode_critic_rating_update: mdb_tomatoes
      mass_episode_audience_rating_update: mdb_tomatoesaudience



playlist_files:
  - default: playlist                # This is a file within Kometa's defaults folder
    template_variables:
      libraries: Movies, TV Shows    # list of libraries that you want the Kometa Defaults playlists to look at
  

settings:
  run_order:
  - operations
  - metadata
  - collections
  - overlays
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: true
  asset_depth: 1
  create_asset_folders: true
  prioritize_assets: false
  dimensional_asset_rename: false
  download_url_assets: true
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: sync
  minimum_items: 2
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: true
  run_again_delay: 60
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: false
  show_unconfigured: true
  show_filtered: false
  show_options: false
  show_missing: true
  show_missing_assets: true
  save_report: false
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_users: all
  playlist_exclude_users:
  playlist_report: false
  verify_ssl: true
  custom_repo: https://raw.githubusercontent.com/nwithan8/configs/main/plex/pmm/
  overlay_artwork_filetype: jpg
  overlay_artwork_quality: 75
webhooks:                            # Can be individually specified per library as well
  error:
  version:
  run_start:
  run_end:
  changes:
plex:                                # Can be individually specified per library as well; REQUIRED for the script to run
  url: http://10.10.0.12:32400
  token: V8kHYTRGwU_xWr4Smvxy
  timeout: 60
  db_cache:
  clean_bundles: false
  empty_trash: false
  optimize: false
  verify_ssl:
tmdb:                                # REQUIRED for the script to run
  apikey: 1f3173b522d8e27216611169535c3533
  language: en
tautulli:                            # Can be individually specified per library as well
  url: http://10.10.0.12:8181
  apikey: 08e5b35efa5040b69f04392ce1d94b20
github:
  token: ################################
omdb:
  apikey: 1fa3a32d
  cache_expiration: 60
mdblist:
  apikey: clj1fqrebwbpja5xbf5fin7ai
  cache_expiration: 60
notifiarr:
  apikey: dd4b23b5-282f-49f7-abe9-4f873f1864ab
# gotify:
#   url: http://192.168.1.12:80
#   token: ####################################
# anidb:                               # Not required for AniDB builders unless you want mature content
#   username: flapj4cks
#   password: ZRQeCgcYa66zaq
radarr:                              # Can be individually specified per library as well
  url: http://10.10.0.12:7878
  token: dc8bf48c6d794f4f9b6c72d50c3e058e
  add_missing: false
  add_existing: false
  upgrade_existing: false
  monitor_existing: false
  root_folder_path: "/data/media/movies"
  monitor: true
  availability: announced
  quality_profile: TRaSH - Low
  tag:
  search: false
  radarr_path:
  plex_path:
sonarr:                              # Can be individually specified per library as well
  url: http://10.10.0.12:8989
  token: f7cb62dc35b7487b892f3fe6f5b5e724
  add_missing: false
  add_existing: false
  upgrade_existing: false
  monitor_existing: false
  root_folder_path: "/data/media/tv"
  monitor: all
  quality_profile: WEB-DL (Trash)
  language_profile: English
  series_type: standard
  season_folder: true
  tag:
  search: false
  cutoff_search: false
  sonarr_path:
  plex_path:
########## GENERATED BY TRAKTAUTH ##########
trakt:
  client_id: d237a1787690ac6040da0af41cf20c77d91f5789cfd9dea6c247b5f15f930e6b
  client_secret: b178bb9a172eb63720559dafc09adf5ae9020d531376c5342d302f8351dac47f
  authorization:
    access_token: 0a4bd118a63b48e3f569b113ac2046220bbfda4c7178212d63cc575a6dcf7ddc
    token_type: Bearer
    expires_in: 7889237
    refresh_token: d1083bf9e7dc5b0c7b0d6dbe1f4eb282b0376803081d5bb0cae57a5c9a066d24
    scope: public
    created_at: 1722995732
  pin:
############################################
mal:
  client_id: ####################
  client_secret: ####################
  authorization:
    # everything below is autofilled by the script
    access_token:
    token_type:
    expires_in:
    refresh_token:
